DROP TABLE IF EXISTS game_data

CREATE TABLE game_data (
  id NUMBER AUTO_INCREMENT  PRIMARY KEY,
  current_player VARCHAR(250) DEFAULT NULL,
  pit_index INT DEFAULT NULL,
  p1_pits VARCHAR(500) NOT NULL,
  p2_pits VARCHAR(500) NOT NULL,
  winner VARCHAR(250) DEFAULT NULL
);

